export const AppointmentLists = [
  {
    id: "D1001",
    name: "Dr. Maria Santos",
    specification:
      "Psychologist, General Medicine, Preventive Medicine, Primary Care",
    avatar: "https://avatar.iran.liara.run/public/boy",
    experience: "4",
    date: "March 01, 2003",
    time: "02:05 pm",
    status: "Completed",
    price: "500",
  },
  {
    id: "D1002",
    name: "Dr. Juan Dela Cruz",
    specification: "Cardiology, Internal Medicine",
    avatar: "https://avatar.iran.liara.run/public/girl",
    experience: "7",
    date: "April 15, 2005",
    time: "10:20 am",
    status: "Pending",
    price: "650",
  },
  {
    id: "D1003",
    name: "Dr. Anna Reyes",
    specification: "Dermatology, Primary Care",
    avatar: "https://avatar.iran.liara.run/public/boy",
    experience: "5",
    date: "June 10, 2010",
    time: "03:45 pm",
    status: "OnCall",
    price: "700",
  },
  {
    id: "D1004",
    name: "Dr. Michael Cruz",
    specification: "Orthopedics, Sports Medicine",
    avatar: "https://avatar.iran.liara.run/public/girl",
    experience: "9",
    date: "August 23, 2008",
    time: "09:15 am",
    status: "RoomCreated",
    price: "800",
  },
  {
    id: "D1005",
    name: "Dr. Sophia Lim",
    specification: "Pediatrics, Preventive Medicine",
    avatar: "https://avatar.iran.liara.run/public/boy",
    experience: "3",
    date: "January 12, 2012",
    time: "01:30 pm",
    status: "Paid",
    price: "550",
  },
  {
    id: "D1006",
    name: "Dr. Robert Gomez",
    specification: "General Surgery, Emergency Medicine",
    avatar: "https://avatar.iran.liara.run/public/girl",
    experience: "11",
    date: "May 05, 2000",
    time: "11:10 am",
    status: "Completed",
    price: "900",
  },
  {
    id: "D1007",
    name: "Dr. Carla Mendoza",
    specification: "Neurology, General Medicine",
    avatar: "https://avatar.iran.liara.run/public/boy",
    experience: "6",
    date: "October 29, 2007",
    time: "04:25 pm",
    status: "Pending",
    price: "720",
  },
  {
    id: "D1008",
    name: "Dr. Kevin Santos",
    specification: "ENT, Primary Care",
    avatar: "https://avatar.iran.liara.run/public/girl",
    experience: "4",
    date: "September 14, 2015",
    time: "08:40 am",
    status: "RoomCreated",
    price: "600",
  },
  {
    id: "D1009",
    name: "Dr. Angela Torres",
    specification: "Psychiatry, Preventive Medicine",
    avatar: "https://avatar.iran.liara.run/public/boy",
    experience: "8",
    date: "February 17, 2009",
    time: "05:55 pm",
    status: "Paid",
    price: "750",
  },
  {
    id: "D1010",
    name: "Dr. David Castillo",
    specification: "General Medicine, Family Medicine",
    avatar: "https://avatar.iran.liara.run/public/girl",
    experience: "10",
    date: "July 07, 2011",
    time: "12:10 pm",
    status: "OnCall",
    price: "680",
  },
];
