export const DoctorList = [
  {
    id: "D1001",
    name: "Dr. Maria Santos",
    specification:
      "Psychologist, General Medicine, Preventive Medicine, Primary Care",
    avatar: "https://avatar.iran.liara.run/public/boy",
    experience: "4",
    graduatedAt: "Harvard University",
    status: "online",
    price: "500",
  },
  {
    id: "D1002",
    name: "Dr. John Reyes",
    specification: "Cardiologist, Internal Medicine, Preventive Care",
    avatar: "https://avatar.iran.liara.run/public/girl",
    experience: "8",
    graduatedAt: "Stanford University",
    status: "offline",
    price: "700",
  },
  {
    id: "D1003",
    name: "Dr. Angela Cruz",
    specification: "Dermatologist, Cosmetic Medicine",
    avatar: "https://avatar.iran.liara.run/public/boy",
    experience: "6",
    graduatedAt: "University of Oxford",
    status: "oncall",
    price: "600",
  },
  {
    id: "D1004",
    name: "Dr. Michael Tan",
    specification: "Orthopedic Surgeon, Sports Medicine",
    avatar: "https://avatar.iran.liara.run/public/girl",
    experience: "10",
    graduatedAt: "University of Toronto",
    status: "online",
    price: "900",
  },
  {
    id: "D1005",
    name: "Dr. Sophia Lim",
    specification: "Pediatrician, Neonatology",
    avatar: "https://avatar.iran.liara.run/public/boy",
    experience: "5",
    graduatedAt: "University of Melbourne",
    status: "offline",
    price: "550",
  },
  {
    id: "D1006",
    name: "Dr. Daniel Garcia",
    specification: "Neurologist, Psychiatry",
    avatar: "https://avatar.iran.liara.run/public/girl",
    experience: "12",
    graduatedAt: "Johns Hopkins University",
    status: "oncall",
    price: "1000",
  },
  {
    id: "D1007",
    name: "Dr. Emily Ramos",
    specification: "Endocrinologist, Diabetes Specialist",
    avatar: "https://avatar.iran.liara.run/public/boy",
    experience: "7",
    graduatedAt: "Cambridge University",
    status: "online",
    price: "650",
  },
  {
    id: "D1008",
    name: "Dr. Robert Mendoza",
    specification: "Oncologist, Internal Medicine",
    avatar: "https://avatar.iran.liara.run/public/girl",
    experience: "9",
    graduatedAt: "Yale University",
    status: "offline",
    price: "1200",
  },
  {
    id: "D1009",
    name: "Dr. Jessica Navarro",
    specification: "Gynecologist, Obstetrics",
    avatar: "https://avatar.iran.liara.run/public/boy",
    experience: "11",
    graduatedAt: "Columbia University",
    status: "oncall",
    price: "750",
  },
  {
    id: "D1010",
    name: "Dr. David Cruz",
    specification: "Pulmonologist, Critical Care Medicine",
    avatar: "https://avatar.iran.liara.run/public/girl",
    experience: "15",
    graduatedAt: "University of California, Los Angeles",
    status: "online",
    price: "1300",
  },
  {
    id: "D1011",
    name: "Dr. Hannah Lopez",
    specification: "Ophthalmologist, Vision Science",
    avatar: "https://avatar.iran.liara.run/public/boy",
    experience: "6",
    graduatedAt: "McGill University",
    status: "offline",
    price: "500",
  },
  {
    id: "D1012",
    name: "Dr. Anthony Delgado",
    specification: "ENT Specialist, Head and Neck Surgery",
    avatar: "https://avatar.iran.liara.run/public/girl",
    experience: "13",
    graduatedAt: "University of Michigan",
    status: "oncall",
    price: "950",
  },
  {
    id: "D1013",
    name: "Dr. Grace Villanueva",
    specification: "Rheumatologist, Internal Medicine",
    avatar: "https://avatar.iran.liara.run/public/boy",
    experience: "8",
    graduatedAt: "University of Sydney",
    status: "online",
    price: "600",
  },
  {
    id: "D1014",
    name: "Dr. Kevin Bautista",
    specification: "Gastroenterologist, Digestive Health",
    avatar: "https://avatar.iran.liara.run/public/girl",
    experience: "14",
    graduatedAt: "Duke University",
    status: "offline",
    price: "1100",
  },
  {
    id: "D1015",
    name: "Dr. Olivia Flores",
    specification: "Allergist, Immunologist",
    avatar: "https://avatar.iran.liara.run/public/boy",
    experience: "5",
    graduatedAt: "University of Edinburgh",
    status: "oncall",
    price: "520",
  },
  {
    id: "D1016",
    name: "Dr. Patrick Ramos",
    specification: "Hematologist, Oncology",
    avatar: "https://avatar.iran.liara.run/public/girl",
    experience: "9",
    graduatedAt: "Imperial College London",
    status: "online",
    price: "980",
  },
  {
    id: "D1017",
    name: "Dr. Camille Santos",
    specification: "Family Medicine, Primary Care",
    avatar: "https://avatar.iran.liara.run/public/boy",
    experience: "4",
    graduatedAt: "University of British Columbia",
    status: "offline",
    price: "480",
  },
  {
    id: "D1018",
    name: "Dr. Steven Morales",
    specification: "Nephrologist, Kidney Specialist",
    avatar: "https://avatar.iran.liara.run/public/girl",
    experience: "16",
    graduatedAt: "University of Chicago",
    status: "oncall",
    price: "1400",
  },
  {
    id: "D1019",
    name: "Dr. Laura Gutierrez",
    specification: "Radiologist, Imaging Specialist",
    avatar: "https://avatar.iran.liara.run/public/boy",
    experience: "7",
    graduatedAt: "University of Zurich",
    status: "online",
    price: "700",
  },
  {
    id: "D1020",
    name: "Dr. Peter Castillo",
    specification: "Anesthesiologist, Pain Management",
    avatar: "https://avatar.iran.liara.run/public/girl",
    experience: "18",
    graduatedAt: "University of Pennsylvania",
    status: "offline",
    price: "1500",
  },
];
